### PR TITLE
shields added into README.md file

### PR DESCRIPTION
**Pull request by akash19coder**
## Changes proposed

           The changes involve the addition of shields in the README.md file 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
shield

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
Nice work!

I'd love to get an opinion from @eddiejaoude on which we want to display. I feel like the ones for open issues and open PRs are kind of redundant, because they are shown in Github above as well. Let me know what you think :)

**Comment by akash19coder** [comment]
@Cahllagerfeld I feel the same I should probably remove open issues and open PRs because it is readily available in Github. Instead, adding something else that is more helpful for contributors would be a good idea 😄

**Review by Cahllagerfeld — COMMENTED** [review]
I feel like an indicator if the actions are passing would be helpful :)

**Comment by akash19coder** [comment]
@Cahllagerfeld I have removed some badges and added some. Please take a look at it.

### Previous
shield

### Present
badge

**Review by Cahllagerfeld — APPROVED** [review]
Nice work!

**Pull request merged**
