### PR TITLE
Added filter modal

### LINKED ISSUE #215: [FEATURE] Move Filters to Modal
### Description

Currently the list of filters might become quite long + in addition when having additional filters, e.g the one for languages, the space this entire filter thing takes in might become very big. We should htink about moving the filter stuff to modals so they don't block the actual UI

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rprav-n**
## Fixes Issue

Closes #215

### Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Video: 

https://user-images.githubusercontent.com/46050644/230729011-f3cb4b62-472f-4ed4-8354-18ce58d69d6f.mp4

### CODE REVIEW

**Review by patel-aum — APPROVED** [review]

**Review by Cahllagerfeld — COMMENTED** [review]
Really nice work! Sorry for taking a while for review: 
 The only thing that I saw, is that the modal should also close when pressing the esc-button. Other than that its looking good to me 👍

**Comment by rprav-n** [comment]
@Cahllagerfeld Thanks.

> Sorry for taking a while for review:

No worries.

> modal should also close when pressing the esc-button

Sure, will do that.

**Comment by rprav-n** [comment]
@Cahllagerfeld 

**Added**: On pressing esc-button the modal should close functionality.

**Video:**

https://user-images.githubusercontent.com/46050644/232233990-71a8fb54-1e6c-4dcf-8469-90803384c408.mov

**Review by Cahllagerfeld — APPROVED** [review]
Nice work!

**Pull request merged**
