### PR TITLE
Changing the PR-link of CONTRIBUTING.md file 

### PR DESCRIPTION
**Pull request by yoursmanjunad**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers
I've updated the link mentioned in the description (94th line).

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Which issue is this PR related to? 😅

**Comment by yoursmanjunad** [comment]
Hey, are the recently revised guidelines file acceptable? Or should I put in more effort to improve it further?

**Comment by yoursmanjunad** [comment]
I actually mentioned in this [conversation](https://github.com/EddieHubCommunity/good-first-issue-finder/issues/324#issue-1681596338) that you improve and adapt your present CONTRIBUTING.md file because there is so much redundant information there that it would be confusing for new contributors. I've chosen to edit the file and make it minimal because I'm one of the new contributors and it will be useful for novices.

**Comment by Cahllagerfeld** [comment]
Hey @eddiejaoude, what are your thoughts on this? I'm not sure about all these changes to the contributing file. Let me know what you think 👍

**Comment by Cahllagerfeld** [comment]
I'll close the PR for now then, thanks Eddie 👍

**Pull request closed without merging**
