### PR TITLE
fix: Text cut off on mobile

### LINKED ISSUE #100: Text cut off on mobile
### Description

Too much text is cut off from each issue on mobile (screenshot from iPhone XS) especially when there is also a label. Suggestion: text should wrap onto next line instead of be cut off. 

### Screenshots

72B2D91E-99D2-44AE-8BD1-D8747CCC075F

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by realtouseef**
closes #100
- made other small UI changes to the `issue-card`

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/116"></a>

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Could you please remove your`yarn.lock` from the PR 👍

**Comment by realtouseef** [comment]
@Cahllagerfeld deleted the `yarn.lock`

**Review by schmelto — APPROVED** [review]
## Looking good to me

### TLDR;

Thank you for the PR. Your suggested changes looking good to me.


---

### Full details

Thank you for the PR. Your suggested changes looking good to me.
Feel free to checkout other issues. 

---

- Languages: all
- Labels: Style guide

**Review by Pradumnasaraf — APPROVED** [review]
LGTM!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by emmalearnscode — APPROVED** [review]
Thanks for having a go at this issue, it looks good to me 👍 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by krshdev — APPROVED** [review]

**Review by Susmita-Dey — APPROVED** [review]
LGTM!

🏆Summary: This code looks good to me. 👌 Thanks fir the contribution. 😊

**Review by Cahllagerfeld — APPROVED** [review]
Awesome, thanks for removing the lockfile

**Pull request merged**
