### PR TITLE
Adjust title

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Fixes part of #43 

@Cahllagerfeld Not linking the issue in this PR has this only adjusts the title on the favicon.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/98"></a>

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
Please focus on the last commit, the first 3 are from my previous PR.. I commited in main instead of a branch in my last PR, acciedently.

**Comment by emmalearnscode** [comment]
> Please focus on the last commit, the first 3 are from my previous PR.. I commited in main instead of a branch in my last PR, acciedently.

Hi Kendall, you need to revert the previous commits so that only the title change is in this PR. At the moment it also includes the PR template

**Comment by KendallDoesCoding** [comment]
> > Please focus on the last commit, the first 3 are from my previous PR.. I commited in main instead of a branch in my last PR, acciedently.
> 
> Hi Kendall, you need to revert the previous commits so that only the title change is in this PR. At the moment it also includes the PR template

Oh yeah, the PR template is not merged yet, I'll transfer the repo and figure it out, please wait for a bit... Thanks

**Comment by Cahllagerfeld** [comment]
Closing this in favour of #113

**Pull request closed without merging**
