### PR TITLE
Remove navbar

### LINKED ISSUE #145: [OTHER] Does this site actually need a nav component?
### What would you like to share?

Since there is currently only one page and the nav component links back to itself, this could be confusing for screen reader users.

I suggest we remove the nav component and the Hubber icon can just be a part of the header and not be a link unless it is intended to add more pages.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dharmik48**
## Fixes Issue

Closes #145 

## Changes proposed

Removes the nav element and moves the Hubber icon and theme switcher to the `header`

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Desktop Screenshot:
desktop size screenshot

Mobile Screenshot:
mobile size screenshot

## Note to reviewers

\-

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/165"></a>

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
Nice work 🚀 
At least for me the navbar looks too narrow on mobile devices, especially the centered headline with the Theme-Switcher. Should we create a hamburger menu and hide the Theme Switcher there on mobile, or should we move it somewhere else? What do think about that?
grafik

**Comment by Dharmik48** [comment]
Ya actually that was the most tricky part for me to figure out. 

I don't think a hamburger menu is necessary just for a single theme swither. I have a better idea, what if we make the 3 icons vertical on smaller screen size?

Something like this:
image

**Comment by Cahllagerfeld** [comment]
Wow, that looks awesome!! Only a small thing, please make sure there's enough space between the icons, so people are able to use them with a touch gesture.

**Comment by Dharmik48** [comment]
Hey @Cahllagerfeld made those changes, please review it when you get time 😀

**Comment by Dharmik48** [comment]
mobile screenshot

**Review by Cahllagerfeld — APPROVED** [review]
Looks good to me, lets get it merged 🎉

**Pull request merged**
