### PR TITLE
Fix: made changes to open links in new tab.

### PR DESCRIPTION
**Pull request by dhruv1345**
I have made changes in the readme file so as to open the links which are mentioned in the new tab.  So, that user can use both tabs with using the back and forth buttons.

## Fixes Issue
Redirecting websites in a new tab instead of opening them in the same.

## Changes proposed

I have added {target="_blank"} after the third party links, so that they open in new tabs without closing the github profile of EddieHubCommunity.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by dhruv1345** [comment]
I hope I have made the necessary changes and helped the users to get a nice experience. whenever, they read the Readme file.

**Comment by tbhaxor** [comment]
Hi @dhruv1345 thanks for contributing, the links are not opening in the new tab and moreover it is showing the `{:target="_blank"}` in the text

image

The syntax you are using works in the github pages transpiled with Kramdown processor, not with github flavoured processor: https://stackoverflow.com/a/71373125/10362396

**Comment by dhruv1345** [comment]
Okay I'll try to fix it. thanks for informing.

**Comment by Cahllagerfeld** [comment]
closing the PR due to no activity, feel free to reopen if required 👍

**Pull request closed without merging**
