### PR TITLE
docs(license): add MIT license

### LINKED ISSUE #95: [DOCS] Add license
### Description

Add license to project... Maybe it can be MIT?

### Screenshots

_No response_

### Additional information

I can work on this, please share the LICENSE yall want to be added.

### PR DESCRIPTION
**Pull request by hashfx**
## Fixes Issue
Closes #95 

## Changes proposed
+ #### add license

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/121"></a>

### CODE REVIEW

**Comment by hashfx** [comment]
Should it be changed to MIT Open Source License?

**Comment by hashfx** [comment]
Changed License to MIT

**Review by schmelto — APPROVED** [review]
lgtm

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by krshdev — APPROVED** [review]

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Could you please add the MIT-License to the [license-prop](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license) of the `package.json` as well please.

**Review by emmalearnscode — APPROVED** [review]
Great! thanks for contributing!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by Susmita-Dey — APPROVED** [review]
LGTM!

**Review by Cahllagerfeld — APPROVED** [review]
Looks good to me 🚀

**Pull request merged**
