### PR TITLE
Updated Preview

### PR DESCRIPTION
**Pull request by Bashamega**
Hello:)

I have update the preview image.

### CODE REVIEW

**Comment by Bashamega** [comment]
Hello @eddiejaoude :) Can you please merge this pr

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍 

*Please note: avoid tagging and extra notifications, it has not even been 24 hours yet*

**Comment by Bashamega** [comment]
Your welcome:)

I will not tag again

**Comment by eddiejaoude** [comment]
thank you! I get many notifications so it can take me sometime to catch up on then, but if it is 1+ week then yes please tag me here or EddieHub Discord, because I do sometimes miss notifications http://discord.eddiehub.org

**Pull request merged**
