### PR TITLE
change favicon

### LINKED ISSUE #43: adjust favicon & title

### LINKED ISSUE #60: [FEATURE] Update favicon file format
### Description

Update "favicon.png" to "favicon.ico"

I would love to work on this, please assign me.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dharmik48**
## Fixes Issue

Closes #43 
Closes #60 

## Changes proposed

Changed the favicon from the default Svelte to one of the Hubbers from the [Branding repo](https://github.com/EddieHubCommunity/Branding).

The favicon is a `.ico` file, so #60 is also fixed.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/158"></a>

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
It's technically already working 🚀 One small nit: Hubber looks quite narrow. This is caused by the image thats not a square. Could you turn into a square, so we don't have any strange looking dimensions, and hubber stays consistent :D Let me know if you need help with this :) 
grafik

**Comment by Dharmik48** [comment]
My bad I didn't notice that😅 though I can fix that right away! 

But I have one question, how do I edit the code/files on this PR? Or do I have to raise a new PR for the changes?

**Comment by schmelto** [comment]
> My bad I didn't notice that😅 though I can fix that right away! 
> 
> 
> 
> But I have one question, how do I edit the code/files on this PR? Or do I have to raise a new PR for the changes?

You can just edit the forked in your forked repo in the branch main and commit them their this will automatically update the files in this pr

**Comment by Dharmik48** [comment]
Can you check it now? Does it look better?

> > My bad I didn't notice that😅 though I can fix that right away!
> > But I have one question, how do I edit the code/files on this PR? Or do I have to raise a new PR for the changes?
> 
> You can just edit the forked in your forked repo in the branch main and commit them their this will automatically update the files in this pr

Got it! Thanks for the help 😊

I made the changes, so can you look it up? Is it better now?

**Comment by Dharmik48** [comment]
@Cahllagerfeld I have made the changes, please review the code when you get time 😊

**Comment by Dharmik48** [comment]
Here's a before and after image comparison:

Before:                                                                                                                                                                                      
image 

After:
image

**Comment by Dharmik48** [comment]
> I am a bit confused now... I can't see the favicon neither in firefox, nor in chrome :o @schmelto Could you please validate if the favicon works for you? grafik

I caught the bug, It should be fixed now. 

Sorry for the mistake 😅

**Comment by Dharmik48** [comment]
By mistake, I put the `favicon.ico` in `/static/images` but it should be in `/static`

Moved it back to its original place, and it's working!

**Review by Cahllagerfeld — APPROVED** [review]
Awesome, nice work 🚀

**Comment by Dharmik48** [comment]
Glad to be the part of the community😄

**Comment by eddiejaoude** [comment]
Great work and collaboration everyone 🎉

**Comment by Dharmik48** [comment]
> Great work and collaboration everyone 🎉 

Thank you Eddie 😄

**Pull request merged**
