### PR TITLE
Move the div above the header inside the header

### LINKED ISSUE #102: [OTHER] Use header tag instead of div tag
### What would you like to share?

Use a header tag around the title, toggle and search bar instead of a div to improve the semantics of the site.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Benmuiruri**
## Fixes Issue #102 
This PR Closes #102 

## Changes proposed
The changes in this PR proposes moving the `div` above the `header` containing the text _Eddiehub issue-crawler for finding good first issues_ inside the `header` to improve the semantics of the `HTML` structure

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

header-fix

## Note to reviewers
The above screenshot shows the div which I moved inside the `header` tag. 
Cheers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/144"></a>

### CODE REVIEW

**Review by emmalearnscode — APPROVED** [review]
This looks good 👍 Thanks for contributing!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Comment by Benmuiruri** [comment]
Hi @emmalearnscode thanks for the review. There seems to be some errors with the checks. Any idea what they could be?

**Comment by emmalearnscode** [comment]
I've asked some of the other maintainers to have a look at it. They were adding some extra features to the repositories yesterday to collect statistics but it seems there might be a bug somewhere. I don't think it's anything you need to worry about :)

**Comment by eddiejaoude** [comment]
Please ignore the failing `statistics` GitHub Actions

Maintainers when you want to merge you should be able to merge even with the failing Action, any issues let me know

Note: the Action has now be removed, so will not happen in the future

**Review by krshkodes — APPROVED** [review]
Understood Eddie! This looks good to me!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Readable, Efficient, Elegant, Maintainable

**Pull request merged**
