### PR TITLE
Change avatars

### LINKED ISSUE #82: [FEATURE] Dynamic Image On Issue
### Description

image

Currently, it is just github logo, could be

- the pfp of the issue author
- pfp of the repo owner

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dharmik48**
## Fixes Issue

Closes #82 

## Changes proposed

Made some changes so now instead of the GitHub icon for every issue, it will show the avatar of the repo owner.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

eddiehub issues

all github issues

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/167"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
So whats your take on it now, do you think it looks better with the avatars, or with the generic and consistent Github-Icon? :)

**Comment by Dharmik48** [comment]
I think that the one with custom avatars looks better. It gives a personal touch to every issue and feels more unique! The GitHub icons also look great, but I am slightly leaning towards the avatars one.

**Comment by Cahllagerfeld** [comment]
What do you think about making the icons as circles?

**Comment by Dharmik48** [comment]
Yeah! That will add a bit of consistency

**Comment by Dharmik48** [comment]
You were right! It does look a bit better. Why didn't it come to my mind😅
image

**Review by Cahllagerfeld — APPROVED** [review]
I'd say lets get it merged!! We can do followup PRs in case we don't want it anymore

**Comment by Dharmik48** [comment]
Yeah we can revert it back if we don't want it any more in tht future

**Pull request merged**
