### PR TITLE
Change Logo and favicon

### PR DESCRIPTION
**Pull request by ianujvarshney**
I Change on this website Logo of website of header section and with change favicon of website to branding page. please merge this change. 

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/168"></a>

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Thanks for your contribution 🚀 , a few comments: 
1. please don't delete `.env.example` => revert the change please
1. please don't delete favicon => revert the change here as well please
1. could you please add `hubber.png` with smaller dimensions, I think we don't need 4000x3873 px for the image, this will increase loading speed, because less data need to be transferred

**Comment by ianujvarshney** [comment]
> Thanks for your contribution rocket , a few comments:
> 
> 1. please don't delete `.env.example` => revert the change please
> 2. please don't delete favicon => revert the change here as well please
> 3. could you please add `hubber.png` with smaller dimensions, I think we don't need 4000x3873 px for the image, this will increase loading speed, because less data need to be transferred

sure

**Comment by ianujvarshney** [comment]
Now is good either something wrong ?

**Review by Cahllagerfeld — APPROVED** [review]
I pushed a small prettier fix, your changes look good 🚀 Lets get it merged 🎉

**Comment by Cahllagerfeld** [comment]
Can I set the PR to `ready for review`? I think its good to go

**Pull request merged**
