### PR TITLE
updated favicon.png to favicon.ico

### PR DESCRIPTION
**Pull request by susheelpal**

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Thanks for raising 🏀 did you test the changes, for me the changes are not working ... Maybe I'm doing something wrong.

**Comment by susheelpal** [comment]
I don't know how to run this project. I thought this is just extension changes. So I have not tested it.

**Comment by Cahllagerfeld** [comment]
We should add a `Contributing.md` then. Do you want to open an issue for this?
Just changing the extensions isn't working unfortunately.

**Comment by susheelpal** [comment]
ya sure. I will create one issue and later will test and request PR for this issue. should I close this PR?

**Comment by Cahllagerfeld** [comment]
If you want to, I'll write the `contributing`-file during the comming weekend. I think you can close the PR as the changes aren't working either and its not that high priority with a need to merge asap, or do you want to leave it open?

**Comment by susheelpal** [comment]
ya will close the issue. I can do it again. not a big change.

**Pull request closed without merging**
