### PR TITLE
doc : added license badge in README.md

### LINKED ISSUE #80: [FEATURE] Add badges to README.md
### Description

Add a couple of badges to README.md, for ex: size, closed pr's, closed issues.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Kartik2220**
Resolve partially #80

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ x] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/172"></a>

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
I think we should add the shields.io badges to a new line, so they are aligned if we add additional ones. Could you please put the badge in a new line :) Other than that the changes are looking good to me 👍

**Comment by Kartik2220** [comment]
> 



> I think we should add the shields.io badges to a new line, so they are aligned if we add additional ones. Could you please put the badge in a new line :) Other than that the changes are looking good to 

thanks doe suggesting

**Comment by Kartik2220** [comment]
@Cahllagerfeld  take a look:)

**Review by Cahllagerfeld — APPROVED** [review]
Awesome, thank you! 🚀

**Pull request merged**
