### PR TITLE
Update theme-switcher.svelte

### PR DESCRIPTION
**Pull request by avinashji1302**
## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## Note to reviewers

  Please check .....If there is any mistake please let me know

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Which issue is this related to?

**Comment by avinashji1302** [comment]
> Which issue is this related to?

Not a issue ....just some update  the light switcher ......now we only need one button to switch light from dark to light

**Comment by Cahllagerfeld** [comment]
Please open an issue before creating a Pull Request, we had a similar discussion in #352 before with @eddiejaoude that was closed. I tend to close this PR as well, as it drops functionality that is already there

**Review by Cahllagerfeld — COMMENTED** [review]
How would you handle the system default theme with this approach?

**Comment by avinashji1302** [comment]
> Please open an issue before creating a Pull Request, we had a similar discussion in #352 before with @eddiejaoude that was closed. I tend to close this PR as well, as it drops functionality that is already there

I am sorry i didn't know it.... Thanks  letting me know!

**Comment by avinashji1302** [comment]
> How would you handle the system default theme with this approach?

Honestly I didn't think this....I just make a button and on clicking it ..it will change the theme light to dark and vice versa...

And it was working fine....so I made a change and  request it

**Comment by Cahllagerfeld** [comment]
Yes, yes I can understand this 👍:). But the current implementation is having more functionality than yours is having, that's why I was asking how you it would work with yours. As I said I'm not too keen on dropping existing features 😅

**Comment by Cahllagerfeld** [comment]
closing this for now

**Pull request closed without merging**
