### PR TITLE
Closes#385 <feature-added-in-login-button-#385>

### LINKED ISSUE #385: [FEATURE] Login Button should be hover like Get started Button
### Description

**Issue Type:**  Feature Request

**Problem:**
Currently, the hover effect on the Login Button does not provide a visually appealing and engaging user experience. It lacks the user-friendly and inviting interaction that the Get Started Button offers.

### Screenshots

Screenshot 2023-10-08 145810
Screenshot 2023-10-08 145833

### Additional information

**Improved user experience:** A consistent hover effect across the platform enhances the overall user experience and encourages user engagement.

**Implementation Steps:**

Identify the existing CSS styles for the Login Button's hover effect.
Analyze the CSS styles for the Get Started Button's hover effect.
Modify the Login Button's CSS styles to match the Get Started Button's hover effect.
Test the updated hover effect to ensure it provides a visually appealing and engaging experience.
Verify the change does not introduce any negative side effects or compatibility issues.

### PR DESCRIPTION
**Pull request by pragyamishra56**
## Fixes Issue:
Improved user experience: A consistent hover effect across the platform enhances the overall user experience and encourages user engagement.

closes #385 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screenshot 2023-10-21 162335

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Bildschirmfoto 2023-10-21 um 19 37 27

For me the orange tones aren't the same. Could you please use the same orange, as we use for the `Get-started` button.

Same applies for the darkmode hover effect 🤔

**Review by pragyamishra56 — COMMENTED** [review]
Sir I've made the changes as mentioned, "it seems the orange tones don't match. Could you please use the same orange color that we use for the 'Get Started' button?" If any additional changes are needed, please let me know Sir

## Screenshot

Screenshot 2023-10-22 125520

**Comment by pragyamishra56** [comment]
@Cahllagerfeld Sir?

**Review by Cahllagerfeld — APPROVED** [review]
I made the last tweak to it, so we can get it merged now 🎉

**Comment by pragyamishra56** [comment]
> I made the last tweak to it, so we can get it merged now 🎉

@Cahllagerfeld Sir, thank you so much

**Pull request merged**
