### PR TITLE
ADD: login tests added

### PR DESCRIPTION
**Pull request by meetwithyash**
## Changes proposed

Added all the tests there were created for Login

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/218"></a>

### CODE REVIEW

**Review by ahmedsilat44 — APPROVED** [review]
Checked the changes and it all looks good 👍

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Thanks for your contribution, it looks very good 🚀 
I thing we may use `data-test-id` for targetting the elements instead of the regular id [[1](https://playwright.dev/docs/selectors#id-data-testid-data-test-id-data-test-selectors)] What do you think?

**Comment by meetwithyash** [comment]
@Cahllagerfeld , Thanks for the suggestions. I will update it ASAP.

**Comment by meetwithyash** [comment]
@Cahllagerfeld , Please check the updates, let me know if there are any other updates needed.

**Review by ahmedsilat44 — COMMENTED** [review]
@meetwithyash Hello there. I am trying to learn how to write tests and I am looking at your commit as a reference. Could you tell me what is the purpose of the Promise.all you made in the 67th line of the login.spec.ts file. I am sorry if this is the wrong place to ask questions as I am new to all this. Thanks anyway 👍

**Review by Cahllagerfeld — APPROVED** [review]
Awesome, nice work!

**Pull request merged**
