### PR TITLE
[Sanjeev] Fix the Unknown file extension ".ts" error in Playwright test caused by "type: module"

### PR DESCRIPTION
**Pull request by ISanjeevKumar**
Fix for #223

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/224"></a>

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
We can't make that change unfortunately, Sveltekit applications are ES-Modules. I guess there needs to be another fix.

I just tested the steps you described in your issue, and for me everything works as intended. Could you check on your machine as well @eddiejaoude please 👀

**Comment by eddiejaoude** [comment]
It worked for me also, I have node `v16.15.1` on Mac

**Comment by MarkusEicher** [comment]
Hi folks. I ran the procedure yesterday and all went smooth. It seems that we need to find the problem on Sanjeevs configuration. Could it be, that he has installed Playwright before and chosen the javascript option? Just an idea, I have no clue if this is an issue.

Screenshot from the Playwright installation docu.

Playwright-options

**Comment by Cahllagerfeld** [comment]
Let us know, if you need further help 👍

**Comment by eddiejaoude** [comment]
> Sveltekit applications are ES-Modules

@ISanjeevKumar thank you for raising but lets keep vanilla Sveltekit configuration as it will create other problems, we can help debug your issue in EddieHub Discord http://discord.eddiehub.org

**Pull request closed without merging**
