### PR TITLE
Adjust color contrast for github-hover-effect

### LINKED ISSUE #315: [OTHER] Improve animation color of github of techstack in dark mode
### What would you like to share?

It would look better if the animation color is changed from black to white in dark mode.

Screenshot 2023-03-20 155605

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rahul0x00**
## Fixes Issue
closes #315 

## Changes proposed

Adjusted color contrast(changed to darkest shade of gray) of github-hover-effect for both the dark mode as well as for the light mode

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Dark Mode 
image
### Light Mode
image

### CODE REVIEW

**Comment by rahul0x00** [comment]
We can also go for another option, the light tint of grey, let me know what looks good(attached some screenshots for your reference)

#### Dark Mode
image

#### Light Mode
image

**Review by Cahllagerfeld — COMMENTED** [review]
The design was using the Github-CI before. 
Would you prefer the darker tone, or the lighter?

**Comment by rahul0x00** [comment]
Let's go with darker tone,it matches the other boxes contrast tone

**Review by Cahllagerfeld — APPROVED** [review]
Sorry, I missed the notification. Looks good to me 👍

**Pull request merged**
