### PR TITLE
[OTHER] Close Profile Info onNavigation #293

### LINKED ISSUE #293: [OTHER] Close Profile Info onNavigation
### What would you like to share?

image

The section popped up with my name, doesn't closes **automatically** even on going back to home page or when I click on Docs link.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Devangyadav26**
## Fixes Issue
Closes #293 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Cahllagerfeld — COMMENTED** [review]
I think we don't need to make it that difficult, we can use Sveltekit-Hooks like described in my [comment](https://github.com/EddieHubCommunity/good-first-issue-finder/issues/293#issuecomment-1422681492) and destroy the popper-instance in either one of them

**Comment by Devangyadav26** [comment]
Yes, I tried that but not getting the proper results. Giving it one more shot

**Comment by Cahllagerfeld** [comment]
I think all it takes, is something like 

```ts
  beforeNavigate(() => {
    displayPopover = false;
    destroyInstance();
  });
```

It's not tested though

**Comment by Devangyadav26** [comment]
Will work on this again facing issues forking the repo again

**Comment by Devangyadav26** [comment]
On implementing   beforeNavigate(() => {
    displayPopover = false;
    destroyInstance();
  }); the profile icon is getting dissapeared, if anyone else has the idea to implent through this can go ahead

**Comment by Cahllagerfeld** [comment]
I'll open a new PR for this issue then 👍

**Pull request closed without merging**
