### PR TITLE
Introduction to YAML: Creating a Kubernetes deployment

### PR DESCRIPTION
**Pull request by AtulRajput01**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/245"></a>

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Hello 👋 
could you elaborate what the purpose of this PR is?
To me it looks like a Spam PR for hacktoberfest. If that is the case, I'm forced to add the spam label, which may disqualify you from hacktoberfest.

**Comment by Cahllagerfeld** [comment]
Unfortunately, I have bad news...
We've had a discussion with the maintainer team, and decided to close that issue, due to the given reasons in my previous comment.

If you still want to contribute to the project, feel free to pick a non-assigned issue!

**Comment by AtulRajput01** [comment]
I am begginer in DevOps and currently learning docker and Kubernetes and trying to contribute to it...

**Comment by eddiejaoude** [comment]
@AtulRajput01 here are some suggestions to get into DevOps in Open Source

- raise an issue on a project first to see if they would like their project Dockerised
- have a look at GitHub Actions, many projects could benefit from automating existing commands

Remember open source is not about adding lines of code or files, but adding value, have fun 🤓

**Pull request closed without merging**
