### PR TITLE
Display Code of Conduct & License

### LINKED ISSUE #204: [FEATURE] Show that it is a "friendly" repo
### Description

Show badges for

- has a license
- has code of conduct
- ...?

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by KlausMikhaelson**
## Fixes Issue

Closes #204
## Check List (Check all the applicable boxes) 

- [ X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ X] All new and existing tests passed.
- [ X] This PR does not contain plagiarized content.
- [ X] The title of my pull request is a short description of the requested changes.

## Screenshots

eddie solved

## Note to reviewers

I am willing to make any changes if they are required ! this is my first pr for eddiehub community so thank you !

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/229"></a>

### CODE REVIEW

**Review by 404Nikhil — APPROVED** [review]

**Review by 404Nikhil — APPROVED** [review]

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Thanks for your contribution 🚀 In general it looks quite good, just some small comments:

The comments are always referring to the screenshot above them
grafik

- The text in lightmode isn't readable
- The badges aren't vertically centered (see badges next to them)




grafik

- On mobile they take up too much space, I think that we should move the badges into the collapsable section where currently the labels are shown, just on mobile though, what do you think?

**Comment by KlausMikhaelson** [comment]
Yeah sounds good will make the changes right away ! 
Thank you !

**Comment by KlausMikhaelson** [comment]
Hey @Cahllagerfeld I have made all the changes accordingly please review it and lmk if there is something that I should change further. Thank you !

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
I think we are very close to getting it merged 🚀 Last small nit: 



grafik

- On mobile it would be better to have the labels display in the section next to the other labels, e.g. `aspect-code`, and not in the card header.

Other than that the changes look very good to me 👍

**Comment by KlausMikhaelson** [comment]
> I think we are very close to getting it merged 🚀 Last small nit:
> 
> grafik
> 
> * On mobile it would be better to have the labels display in the section next to the other labels, e.g. `aspect-code`, and not in the card header.
> 
> Other than that the changes look very good to me 👍

Yeah that should be easy just give me few minutes will make those changes

**Comment by KlausMikhaelson** [comment]
Hey @Cahllagerfeld I have made those changes do lmk if there's anything else to change !
Thank you !

**Review by Cahllagerfeld — APPROVED** [review]
Hey @KlausMikhaelson 👋 
I made a small adjustment to get rid of the custom breakpoints, as we can also use the tailwind ones + I extended the types so the typescript compiler is happy 🎉 
We can get this merged now I think 🛹

**Pull request merged**
