### PR TITLE
Navigation by tab key is added on toggle

### LINKED ISSUE #104: Toggle is not reachable by keyboard navigation
### Description

When using a keyboard to navigate through the site the tab button jumps straight from focussing on the hubber icon link to the search bar and is unable to tab to the toggle.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bishal7679**
Fixes #104 

## Changes proposed

- Navigation by tab key is added on toggle.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

<a href="https://gitpod.io/#https://github.com/EddieHubCommunity/good-first-issue-finder/pull/150"></a>

### CODE REVIEW

**Review by Cahllagerfeld — CHANGES_REQUESTED** [review]
Thanks for having a look into this 🎉.
For me the tab navigation isn't working as intendet. We are able to reach the toggle now with tabs, but we're not able to use the two toggle-options with tabs.

I think thats the intent behind that issue @emmalearnscode right? :) 

screenshot

**Comment by bishal7679** [comment]
@Cahllagerfeld yes you are right. Actually I had little bit confusion regarding this. 
and after reaching in this toggle by tab what should be the functionality?
If I press enter on that It will work like eddiehub - github and vice versa????

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by bishal7679** [comment]
@Cahllagerfeld Can you clarify what exactly It should be changed or suggest the code I have to add?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by emmalearnscode** [comment]
> @Cahllagerfeld yes you are right. Actually I had little bit confusion regarding this. and after reaching in this toggle by tab what should be the functionality? If I press enter on that It will work like eddiehub - github and vice versa????
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  ❓ I have a question

After tabbing to the toggle button pressing on the space bar should toggle between the github and eddiehub values, essentially pressing space bar checks and unchecks the underlying checkbox.

**Comment by Cahllagerfeld** [comment]
Just asking if you need help with fixing the issue

**Comment by bishal7679** [comment]
@Cahllagerfeld how to enable that feature like with space button toggle will function?
It will be helpful!

**Comment by Cahllagerfeld** [comment]
I think its the easiest to transform the relevant elements into buttons, because they are having a native tabindex

**Comment by emmalearnscode** [comment]
Technically the checkbox should have the tabindex too, it's just unusual why it can't be reached. I wonder if there's something in how the labels are set up which stop the checkbox from being tabbed to.

There is a very comprehensive explanation here: https://kittygiraudel.com/2021/04/05/an-accessible-toggle/#:~:text=Toggles%20(or%20sometimes%20%E2%80%9Ctoggle%20switches,inaccessible%20one%20way%20or%20another.

But I understand if it is too complicated (she goes into lots of detail!)

I am going to look at making a toggle within the next couple of days in another project. If I find a simplified version I will let you know.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Cahllagerfeld** [comment]
We could refactor this Toggle entirely.. By transerring the elements from checkbox + labels to `<a>` we could leverage `sveltekit:prefetch` for performance optimization

**Comment by emmalearnscode** [comment]
> We could refactor this Toggle entirely.. By transerring the elements from checkbox + labels to `<a>` we could leverage `sveltekit:prefetch` for performance optimization

But anchor tags are entirely the wrong semantic element to use as you are not linking to another page. Buttons would be preferable over anchors because they are performing an action if you would really prefer to refactor it and not use a checkbox toggle

**Comment by Cahllagerfeld** [comment]
We're technically doing a URL redirect by checking and unchecking the checkbox. The event handler calls a different URL

**Comment by emmalearnscode** [comment]
> We're technically doing a URL redirect by checking and unchecking the checkbox. The event handler calls a different URL. We're switching Query-Params

It's not really about the URL, it's about what happens on screen and what the user that can't see the screen expects to happen. If it's a link the user expects to be redirected to another section of the page or a new page. That doesn't happen. If it's a link the user will be able to right click it to open in a new window. That doesn't make sense in this case. It will also get psuedo states like active and visited which don't make sense either.

Clicking on it updates the data shown on the screen, it performs an action and therefore a button is the most appropriate element semantically. But if you really do want to use links then they will need role="button" and they will need to be programmed to work like buttons so that they activate on  space keys as well as enter etc.

**Comment by Cahllagerfeld** [comment]
Now I see the point, sorry for causing confusion...
I'd say let's go with buttons then 🤔 For running the load function we should use the `prefetch`-function from `$app/navigation` then I guess.

**Comment by Cahllagerfeld** [comment]
Do you need help with this @bishal7679? Let me know if I can support you with it

**Comment by bishal7679** [comment]
@Cahllagerfeld Really glad that you will help me
Sounds good😊

**Comment by Cahllagerfeld** [comment]
I suggest refactoring this component to use buttons, as they naturally have a tab-index and also the a11y behavior we need here. The next step could be using the `prefetch`-function for performance optimization. 
Summary
1. Use `<button>` instead of `checkbox`
1. Implement `prefetch` on hover a button

**Comment by Cahllagerfeld** [comment]
closing this for now, due to inactivity. Feel free to reopen! :)

**Pull request closed without merging**
